# Author: Khang Mạnh Tử
language: cpp
compiler:
  - gcc
  # - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  # - sudo apt-get upgrade -y

install:
  - sudo apt-get install g++-4.8 autopoint intltool unzip g++-multilib libc6-dev-i386 tree -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

before_script:
  - git clone -b stable https://github.com/mxe/mxe.git $HOME/mxe
  - MINS=20
  - NUM_JOBS=$((3 * $(grep processor /proc/cpuinfo | wc -l) / 2))
  - echo $NUM_JOBS

script:
  - cd $HOME/mxe
  - while [ $MINS -gt 0 ]; do echo -e "\n$MINS\033[0K\r\n"; sleep 60; MINS=$((MINS-1)); done & make qt5 --jobs=$NUM_JOBS

after_success:
  - tree > tree.txt
  - cd $HOME
  - git config --global user.email "manhtuvjp@gmail.com"
  - git config --global user.name "MT"
  - git clone --quiet --branch=bin https://${GH_TOKEN}@github.com/manhtuvjp/test_mxe.git mxe_bin > /dev/null
  - cd mxe_bin
  - cp -Rf $HOME/mxe/usr .
  - cp -f $HOME/mxe/tree.txt .
  - git add -f .
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to bin"
  - git push -fq origin bin > /dev/null

branches:
  only:
    - master

env:
  global:
    secure: JRU5h1rTXK2WaAmKdyhgrml4WbFDmK/yGa2zR7DrNGGXJFO7JN8ekFSEj3PaC/YD0EEFzNgqT0oXwLKtNkTTmemWE/vwEZpnG0epibqHwj3uY7MJCofMZBrcPb44O/kirROn3mkWlEaEtcb4JDtgPOtIo3dF0el9munl9PM0XBA=
