language: cpp
compiler:
  - gcc
  # - clang

before_install:
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y; fi
  - if [ "$CXX" = "g++" ]; then sudo add-apt-repository ppa:ondrej/php5 -y; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get update -qq; fi
  - if [ "$CXX" = "g++" ]; then sudo apt-get install g++-4.8 libboost-regex-dev zip autopoint autoconf automake bash bison bzip2 cmake flex gettext git g++ gperf intltool libffi-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl patch perl pkg-config python ruby scons sed unzip wget xz-utils g++-multilib libc6-dev-i386 tree p7zip-full -y; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50; fi
  - if [ "$CXX" = "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - CDIR=$(pwd)
  - git clone -b stable https://github.com/mxe/mxe.git $HOME/mxe
  - cd $HOME/mxe
  - secs=40
  - make qt5 -j10 & while [ $secs -gt 0 ]; do echo -ne "$secs\033[0K\r"; sleep 60; secs=$((secs-1)); done
  - make clean
  - tree
  - tree > tree.txt
  - cd $HOME
  - 7z a -mx=9 mxe.7z mxe
  - git config --global user.email "manhtuvjp@gmail.com"
  - git config --global user.name "MT"
  - git clone --quiet --branch=bin https://${GH_TOKEN}@github.com/manhtuvjp/test_mxe.git mxe_bin > /dev/null
  - cd mxe_bin
  - cp $HOME/mxe.7z .
  - cp $HOME/tree.txt .
  - git add -f .
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to bin"
  - git push -fq origin bin > /dev/null
  - echo -e "Done magic with coverage\n"
  - cd $CDIR
  #- export PATH=~/mxe/usr/bin:$PATH
  #- unset `env | grep -vi '^EDITOR=\|^HOME=\|^LANG=\|MXE\|^PATH=' | grep -vi 'PKG_CONFIG\|PROXY\|^PS1=\|^TERM=' | cut -d '=' -f1 | tr '\n' ' '`
 # - $DIR/usr/i686-pc-mingw32/qt5/bin/qmake

#branches:
#  only:
#    - mxe_test

script:
  - ls -a
  - tree
  
notifications:
  email:
    recipients:
      - manhtuvjp@gmail
      - hoaiphong95@gmail
    on_success: always
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#manhtu"
      - "chat.freenode.net##manhtu"
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{message}"
      - "Change view : %{compare_url}"
      - "Build details : %{build_url}"
    on_success: always
    on_failure: always
env:
  global:
    secure: JRU5h1rTXK2WaAmKdyhgrml4WbFDmK/yGa2zR7DrNGGXJFO7JN8ekFSEj3PaC/YD0EEFzNgqT0oXwLKtNkTTmemWE/vwEZpnG0epibqHwj3uY7MJCofMZBrcPb44O/kirROn3mkWlEaEtcb4JDtgPOtIo3dF0el9munl9PM0XBA=
