# Author: Khang Mạnh Tử
language: cpp
compiler:
  - gcc
  # - clang

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  #- sudo apt-get upgrade -y

install:
  - sudo apt-get install g++-4.8 g++-4.8-multilib autopoint libc6-dev-i386 gperf tree autoconf automake bash bison bzip2 cmake flex gettext git intltool libffi-dev libtool libltdl-dev libssl-dev libxml-parser-perl make openssl patch perl pkg-config scons sed unzip wget xz-utils -y
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50

before_script:
  - git clone --branch=master https://github.com/mxe/mxe.git $HOME/mxe
  - MINS=30
  - NUM_JOBS=$(grep processor /proc/cpuinfo | wc -l)
  - echo $NUM_JOBS

script:
  - cd $HOME/mxe
  - while [ $MINS -gt 0 ]; do echo -e "\n$MINS\033[0K\r\n"; sleep 60; MINS=$((MINS-1)); done & make qt5 opencv --jobs=$NUM_JOBS MXE_TARGETS=x86_64-w64-mingw32
  - git clone --quiet --depth=1 --branch=bin https://${GH_TOKEN}@github.com/manhtuvjp/test_mxe.git mxe_bin > /dev/null
after_success:

  - tree > tree.txt
  - cd $HOME
  - git config --global user.email "manhtuvjp@gmail.com"
  - git config --global user.name "MT"
  - cd mxe/mxe_bin
  - git rm -rf usr > /dev/null
  - cp -Rf $HOME/mxe/usr .
  - cp -f $HOME/mxe/tree.txt .
  - git add -f .
  - git commit -m "Travis build $TRAVIS_BUILD_NUMBER pushed to bin"
  - git push -fq origin bin > /dev/null

branches:
  only:
    - master

env:
  global:
    secure: JRU5h1rTXK2WaAmKdyhgrml4WbFDmK/yGa2zR7DrNGGXJFO7JN8ekFSEj3PaC/YD0EEFzNgqT0oXwLKtNkTTmemWE/vwEZpnG0epibqHwj3uY7MJCofMZBrcPb44O/kirROn3mkWlEaEtcb4JDtgPOtIo3dF0el9munl9PM0XBA=
